conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('resume.urls', namespace='resume')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/urls.py
from django.urls import path

from resume import views
from resume.views import HomePageView, ContactTemplateView, SongListView, SongDownloadView, AboutOneView, ThankYouView
app_name = 'resume'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', views.AboutOneView.as_view(), name='about'),
    path('songs/', views.SongListView.as_view(), name='songs'),
    path('songs/<int:pk>/', views.SongDownloadView.as_view(), name='songs_download'),
    path('contact/', ContactTemplateView.as_view(), name='contact'),
    path('success/',ThankYouView.as_view(), name='success'),


]

resume/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models


class Song(AbstractUser):
    song_name = models.CharField(max_length=200)
    artist_name = models.CharField(max_length=200)
    album_thumbnail = models.ImageField(upload_to='album_thumbnails/', null=True, blank=True)
    audio_file = models.FileField(upload_to='songs/', null=True, blank=True)
    download_count = models.IntegerField(default=0)

    # Related name qo'shish
    groups = models.ManyToManyField(
        Group,
        related_name='song_user_set',  # Bu joyni o'zgartiring
        blank=True,
        help_text='The groups this user belongs to.',
        related_query_name='song_user'
    )

    user_permissions = models.ManyToManyField(
        Permission,
        related_name='song_user_permissions',  # Bu joyni o'zgartiring
        blank=True,
        help_text='Specific permissions for this user.',
        related_query_name='song_user_permission'
    )

    def __str__(self):
        return self.song_name

resume/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

resume/views.py
import os
from django.http import FileResponse, HttpResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, FormView
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.http import HttpResponse
from .models import Song
from .forms import ContactForm
from django.core.mail import send_mail
from django.shortcuts import render
from .models import Song
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

app_name = 'resume'


class HomePageView(TemplateView):
    template_name = 'index-one.html'


class SongListView(ListView):
    model = Song
    template_name = 'songs-one.html'
    context_object_name = 'songs'

    def get_queryset(self):
        return Song.objects.filter(audio_file__isnull=False)


class SongDownloadView(View):
    def get(self, request, pk, *args, **kwargs):
        song = get_object_or_404(Song, pk=pk)

        song.download_count += 1
        song.save()

        response = HttpResponse(song.audio_file, content_type='audio/mpeg')
        response['Content-Disposition'] = f'attachment; filename="{song.song_name}.mp3"'
        return response


class AboutOneView(TemplateView):
    template_name = 'about-one.html'


class ContactTemplateView(FormView):
    template_name = 'contact-one.html'
    form_class = ContactForm
    success_url = reverse_lazy('resume:success')

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        message = form.cleaned_data['message']
        send_mail(
            'Sizga taklifim bor!',
            f'Name: {name}\nEmail: {email}\nMessage: {message}',
            email,
            ['sotvoldiyevazamat193@gmail.com'],
            fail_silently=False,
        )
        return super().form_valid(form)


class ThankYouView(TemplateView):
    template_name = 'succes.html'

templates/contact-one.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>T19</title>

    {% load static %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.2.6/gsap.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">

    <!--favicon-img-->
    <link rel="icon" type="image/png" href="{% static 'img/favicon.jpg' %}">
    <!--favicon-img-->

    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <style>

    </style>

</head>
<body>
<main id="contact-one">

    <!-- CUSTOM CURSOR -->
    <div class="cursor scale"></div>
    <div class="cursor-two scale"></div>
    <!-- CUSTOM CURSOR -->

    <!-- PRELOADER -->
    <div id="preloader">
        <div class="p">
            <img src="{% static 'img/headphone.png' %}" alt="headphone">
        </div>
        <div class="p">T1murov_19</div>
    </div>
    <!-- PRELOADER -->

    <div id="contact-one-content">
        <!-- NAVIGATION -->
        <div class="navigation">
            <div class="logo hover">
                <a href="https://taplink.cc/t1murov_19" target="_blank" rel="noopener noreferrer" class="text">T1murov_19</a>
            </div>
            <div class="menu-bar hover">
                <div class="menu-bar-name text">Menu</div>
                <div class="menu-bar-lines text">
                    <div class="menu-bar-line"></div>
                    <div class="menu-bar-line"></div>
                </div>
            </div>
        </div>
        <!-- NAVIGATION -->

        <!-- HEADING -->
        <div class="heading">
            <div class="text">ALOQA</div>
        </div>
        <!-- HEADING -->

        <div id="flex-row">
            <!-- CONTACT FORM -->
            <div id="contact-form">
                <div id="form" class="opacity-contact">
                    <form action="{% url 'resume:contact' %}" method="post">
                        {% csrf_token %}
                        <div class="mb-1">
                            {{ form.name.label_tag }}
                            {{ form.name }}
                        </div>
                        <div class="mb-1">
                            {{ form.email.label_tag }}
                            {{ form.email }}
                        </div>
                        <div class="mb-1">
                            {{ form.message.label_tag }}
                            {{ form.message }}
                        </div>
                        <button type="submit" id="submit" class="hover">Send</button>
                        <div id="message-error" style="display:none;">Invalid email</div>
                    </form>
                </div>
            </div>
            <!-- CONTACT FORM -->

            <!-- ENQUIRY MAIL -->
           <div id="collaboration-mail" class="opacity-contact">
                <div class="circular-text">
                    <span id="rotated">T1MUROV T1MUROV * &nbsp;&nbsp;&nbsp;&nbsp; T1MUROV T1MUROV * &nbsp;&nbsp;&nbsp;&nbsp;</span>
                </div>
                <div class="mail">
                    <a href="mailto:INFO@GMAIL.COM">T1murov_19</a>
                </div>
            </div>
            <!-- ENQUIRY MAIL -->
        </div>

        <!-- HEADPHONE IMG -->
        <div class="headphone img text">
            <img src="{% static 'img/headphone.png' %}" title="headphone zone" class="text" alt="headphone">
        </div>
        <!-- HEADPHONE IMG -->

        <!-- progress-bar -->
        <div class="progress-bar-container fade-in">
            <div class="progressbar"></div>
        </div>
        <!-- progress-bar -->
    </div>

    <!-- NAVIGATION CONTENT -->
    <div class="navigation-content">
        <div class="navigation-logo hover opacity">
            <a href="https://www.instagram.com/t1murov_19/" target="_blank" rel="noopener noreferrer" class="text">T1murov_19</a>
        </div>
        <ul class="navigation-ul">
                       <li><a href="{% url 'resume:home' %}" data-text="Bosh sahifa">Bosh sahifa</a></li>
                        <li><a href="{% url 'resume:about' %}" data-text="Malumot">Malumot</a></li>
                        <li><a href="{% url 'resume:songs' %}" data-text="Musiqa">Musiqa</a></li>
                        <li><a href="{% url 'resume:contact' %}" data-text="Aloqa">Aloqa</a></li>        </ul>
        <div class="navigation-close hover about-close opacity">
            <div class="navigation-close-line"></div>
            <div class="navigation-close-line"></div>
        </div>

        <div class="project-preview"></div>

        <!-- HEADPHONE IMG -->
        <div class="headphone-navigation opacity">
            <img src="{% static 'img/headphone.png' %}" title="headphone zone" class="text" alt="headphone">
        </div>
        <!-- HEADPHONE IMG -->

        <!-- SOCIAL MEDIA LINKS -->
        <!-- SOCIAL MEDIA LINKS -->
    </div>
    <!-- NAVIGATION CONTENT -->
</main>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/circletype.min.js' %}"></script>
<script src="{% static 'js/jquery.lettering.js' %}"></script>
<script src="{% static 'js/bez.js' %}"></script>
<script src="{% static 'js/pace.js' %}"></script>
<script src="{% static 'js/index.js' %}"></script>
</body>
</html>

templates/index-one.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>T19</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.2.6/gsap.min.js"></script>
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
    
        <!--favicon-img--> 
        <link rel="icon" type="image/png" href="{% static 'img/favicon.jpg' %}">
        <!--favicon-img-->
    
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
    </head>
<body>
    <!-- MAIN CONTENT -->
    <main id="index-one">

          <!-- CUSTOM CURSOR -->
          <div class="cursor scale"></div>
          <div class="cursor-two scale"></div>
          <!-- CUSTOM CURSOR -->

        <!-- PRELOADER -->
        <div id="preloader">
                <img src="{% static 'img/headphone.png' %}" alt="headphone">
                <div class="p">T1murov_19</div>
        </div>
        <!-- PRELOADER -->

<!-- HEADER -->
<div id="header">

    <!-- NAVIGATION -->
    <div class="navigation">
        <div class="logo hover ">
           <a href="https://taplink.cc/t1murov_19" target="_blank" rel="noopener noreferrer" class="text">T1umurov_19</a>
        </div>
        <div class="menu-bar hover ">
            <div class="menu-bar-name text">
                Menu
            </div>
            <div class="menu-bar-lines text">
                <div class="menu-bar-line"></div>
                <div class="menu-bar-line"></div>
            </div>
        </div>
    </div>
    <!-- NAVIGATION -->


    <!-- HEADPHONE IMG -->
    <div class="headphone img text">
        <img src="{% static 'img/headphone.png' %}"  class="text" alt="headphone">
    </div>
    <!-- HEADPHONE IMG -->

    <!-- NEW RELEASE -->
    <div class="new-release img text">
        <img src="{% static 'img/p.jpg' %}" alt="new-release">
        <div class="song-details">
            <div class="song-name">Ber habar</div>
            <div class="singer-name">T1murov_19</div>
            <div class="music-player">
                <div class="play-song">
                    <img src="{% static 'img/play.png' %}" alt="play" data-song="darkfire" class="hover">
                    <audio src="{% static 'music/premyera.mp3' %}" data-audio="darkfire"></audio> <!--LINK AND NAME OF AUDIO YOU WANT TO PLAY-->
                </div>
                <div class="all-songs">
                    <a href="{% url 'resume:songs' %}" title="All Songs"><i class="gg-arrow-right"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- NEW RELEASE -->

</div>
<!-- HEADER -->

<!-- NAVIGATION CONTENT -->
<div class="navigation-content">
    <div class="navigation-logo hover opacity">
        <a href="https://www.instagram.com/t1murov_19/" target="_blank" rel="noopener noreferrer" class="text">T1murov_19</a>
    </div>
    <ul class="navigation-ul">
        <li><a href="{% url 'resume:home' %}" data-text="Bosh sahifa">Bosh sahifa</a></li>
        <li><a href="{% url 'resume:about' %}" data-text="Malumot">Malumot</a></li>
        <li><a href="{% url 'resume:songs' %}" data-text="Musiqa">Musiqa</a></li>
        <li><a href="{% url 'resume:contact' %}" data-text="Aloqa">Contact</a></li>

    </ul>
    <div class="navigation-close hover about-close opacity">
        <div class="navigation-close-line"></div>
        <div class="navigation-close-line"></div>
    </div>

    <div class="project-preview"></div>

    <!-- HEADPHONE IMG -->
    <a href="{% url 'resume:songs' %}" title="headphone zone" class="text" alt="headphone">
        <img src="{% static 'img/headphone.png' %}" alt="headphone">
    </a>

</div>

<!-- NAVIGATION CONTENT -->
</main>
<!-- MAIN CONTENT -->

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bez.js' %}"></script>
<script src="{% static 'js/pace.js' %}"></script>
<script src="{% static 'js/index.js' %}"></script>

</body>
</html>

templates/songs-one.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>T19</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.2.6/gsap.min.js"></script>
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

       <!--favicon-img-->
       <link rel="icon" type="image/png" href="{% static 'img/favicon.jpg' %}">
       <!--favicon-img-->

        <link rel="stylesheet" href="{% static 'css/index.css' %}">
    </head>
<body>
    <main id="songs-one">
        <div class="cursor scale"></div>
        <div class="cursor-two scale"></div>

        <div id="preloader">
            <div class="p">
                <img src="{% static 'img/headphone.png' %}" alt="headphone">
            </div>
            <div class="p">T1murov_19</div>
        </div>

<!-- CONTENT -->
        <div id="songs-one-content">


            <!-- NAVIGATION -->
            <div class="navigation">
                <div class="logo hover">
                    <a href="https://taplink.cc/t1murov_19" target="_blank" rel="noopener noreferrer" class="text">T1murov_19</a>
                </div>
                <div class="menu-bar hover ">
                    <div class="menu-bar-name text">
                        Menu
                    </div>
                    <div class="menu-bar-lines text">
                        <div class="menu-bar-line"></div>
                        <div class="menu-bar-line"></div>
                    </div>
                </div>
            </div>
            <!-- NAVIGATION -->

            <!-- HEADING -->
            <div class="heading">
                <div class="text">
                    Musiqalar
                </div>
            </div>
            <!-- HEADING -->

            <!-- SONGS CONTAINER -->
            <div class="center">
                <div id="songs-container">

                    <!-- SONG -->
                   <div class="songs-list">
    {% for song in songs %}
    <div class="song fade-up">
        <div class="song-img">
            <img src="{{ song.album_thumbnail.url }}" alt="song">
        </div>

        <div class="song-details">
            <div class="song-details-content">
                <div class="song-name">{{ song.song_name }}</div>
                <div class="artist-name">{{ song.artist_name }}</div>
            </div>
            <div class="music-player">
                <div class="play-song mouse">
                    <img id="play-pause-img-{{ song.id }}" src="{% static 'img/play.png' %}" alt="play" class="play-pause-img" data-song="{{ song.song_name }}">
                    <audio id="audio-{{ song.id }}" data-audio="{{ song.song_name }}">
                        <source src="{{ song.audio_file.url }}" type="audio/ogg">
                        <source src="{{ song.audio_file.url }}" type="audio/mp3">
                    </audio>
                </div>
                <div class="download-song mouse">
                    <a href="{{ song.audio_file.url }}" download="{{ song.song_name }} - {{ song.artist_name }}.mp3">
                        <span></span><img src="{% static 'img/download.png' %}" alt="download">
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>



                    <div class="music-indicator">
                        <span style="--i:1;" class="music-indicator-span"></span>
                        <span style="--i:2;" class="music-indicator-span "></span>
                        <span style="--i:3;" class="music-indicator-span "></span>
                        <span style="--i:4;" class="music-indicator-span "></span>
                    </div>

                </div>
            </div>
            <!-- SONGS CONTAINER -->

            <!-- HEADPHONE IMG -->
            <!-- HEADPHONE IMG -->

            <!-- MUSIC INDICATOR -->
            <!-- MUSIC INDICATOR -->

            <!-- progress-bar -->
            <div class="progress-bar-container fade-in">
                <div class="progressbar"></div>
            </div>
            <!-- progress-bar -->

        </div>
        <!-- CONTENT -->

        <!-- NAVIGATION CONTENT -->

        <div class="navigation-content">
            <div class="navigation-logo hover opacity">
                <a href="https://www.instagram.com/t1murov_19/" target="_blank" rel="noopener noreferrer" class="text">T1murov_19</a>
            </div>
            <ul class="navigation-ul">
                       <li><a href="{% url 'resume:home' %}" data-text="Bosh sahifa">Bosh sahifa</a></li>
                        <li><a href="{% url 'resume:about' %}" data-text="Malumot">Malumot</a></li>
                        <li><a href="{% url 'resume:songs' %}" data-text="Musiqa">Musiqa</a></li>
                        <li><a href="{% url 'resume:contact' %}" data-text="Aloqa">Aloqa</a></li>
            </ul>
            <div class="navigation-close hover about-close opacity">
                <div class="navigation-close-line"></div>
                <div class="navigation-close-line"></div>
            </div>

            <div class="project-preview"></div>

            <!-- HEADPHONE IMG -->
            <div class="headphone-navigation opacity">
                <img src="{% static 'img/headphone.png' %}" title="headphone zone" class="text" alt="headphone">
            </div>
            <!-- HEADPHONE IMG -->

        </div>
        <!-- NAVIGATION CONTENT -->

    </main>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bez.js' %}"></script>
    <script src="{% static 'js/pace.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
</body>
</html>

templates/succes.html
<!DOCTYPE html>
{%  load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Sent Successfully</title>
    <style>
       body {
    background-color: black;
    font-family: Arial, sans-serif;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 69vh;
    margin: 0;
}

.success-container {
    background: black;
    padding: 10px;
    border-radius: 10px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    text-align: center;
    max-width: 300px;
    width: 60%;
}

.success-content {
    display: flex;
    flex-direction: column;
    align-items: center;
}

.success-icon {
    width: 100%;
    max-width: 400px;
    height: 200px; /* Adjust height as needed */
    overflow: hidden;
    margin-bottom: 20px;
    position: relative;
}

.success-icon img {
    width: 30%;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}

h1 {
    font-size: 20px; /* Yozuv o'lchami */
    font-family: 'Arial', sans-serif; /* Yozuv uslubi */
    font-weight: bold; /* Yozuv qalinligi */
    color: white; /* Yozuv rangi */
    margin: 30px 0; /* Yozuvning yuqori va pastki qismidagi bo'shliq */
    text-align: center; /* Matnni markazlashtirish */
    text-transform: uppercase; /* Matnni katta harflar bilan yozish */
    letter-spacing: 1px; /* Harflar orasidagi masofa */
}


.btn {
    background-color: #4CAF50;
    color: white;
    padding: 10px 60px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.btn:hover {
    background-color: #45a049;
}

@media (max-width: 600px) {
    .success-container {
        padding: 2px;
    }

    h1 {
        font-size: 20px;
    }

    p {
        font-size: 20px;
    }
}


    </style>
</head>
<body>
    <div class="success-container">
        <div class="success-content">
            <div class="success-icon">
                <img src="{% static 'img/clock.png' %}" alt="Success">
            </div>
            <h1>Habar jonatildi</h1>
            <button id="goBackButton" class="btn">Orqaga</button>
        </div>
    </div>
    <script>
                document.getElementById('goBackButton').addEventListener('click', function() {
            window.history.back();
        });
    </script>
</body>
</html>